assets:
  cachebust: hard

title: Jeff Triplett's Links
name: Jeff Triplett's Links
email: jeff.triplett@gmail.com
description: >
  Thoughts about life, technology, development, and blog by Jeff Triplett.
baseurl: ""
url: https://jefftriplett.com
enforce_ssl: "jefftriplett.com"
relative_permalinks: false
permalink: /:title/
future: true
paginate: 100

# Markdown
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: compressed

github_username:  jefftriplett
twitter_username: webology

# Build settings
#theme: minima
gems:
  # - jekyll-archives
  # - jekyll-coffeescript
  - jekyll-crosspost-to-medium
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock

include:
  - _pages
