version: "3.3"

services:

  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    environment:
      - POST_FOLDER=/srv/jekyll/_posts
    volumes:
      - .:/srv/jekyll

  web:
    image: jekyll/jekyll
    command: jekyll serve --drafts --profile --watch --port 8000
    ports:
      - 8000:8000
    volumes:
      - .:/srv/jekyll
